### ISSUE TITLE
Not really an issue, but it does work on android 4.0.3

### ISSUE THREAD

**Issue by 0n** [DADi590/PS3-Proxy-Server-for-Android#1]
I'll give screenshots when I can, but it does work on 4.0.3 on my lenovo tablet

**Comment by Edw590** [comment]
Hi! Ah but I say that on the notes hahaha. It works only from 4.0.3 upwards. Though, it does not work from 4.0 and bellow.

"This app only works on Android 4.0.3 or newer (I tried to lower as much as I could)!" hahaha.

Bellow that it will not work. You could try some hacks to allow it to work, but I don't know if one thing I use on the app would still be compatible (the thing is the server itself haha). The server requires Android 4.0.3 as minimum. So I made the app to be compatible with all version that I could and still keep the functionality.
