### ISSUE TITLE
Host Update

### ISSUE THREAD

**Issue by dracinn** [DADi590/PS3-Proxy-Server-for-Android#3]
Could you add the ability to host an update like CFW for patched systems?

**Comment by Edw590** [comment]
Hi. Sorry for the delay. You mean like you have the PUP file on your phone and the app would host it so that you could install it on the PS3? (Instead of having to put the file on some real Internet server)

**Comment by Edw590** [comment]
Just to say here too, I posted a reply to your question on PSX-Place: https://www.psx-place.com/threads/ps3-proxy-server-for-android-v2-1-universal.23020/page-2#post-347470, since you there answered the question I made here.
