### ISSUE TITLE
Merge the app in webMAN MOD

### ISSUE THREAD

**Issue by LuanTeles** [DADi590/PS3-Proxy-Server-for-Android#4]
Could you please, add it to webMAN MOD?

**Comment by Edw590** [comment]
Hi. Not sure how I can add an Android app to webMAN. What do you mean more specifically?

**Comment by LuanTeles** [comment]
I'm referring to the fact that webMAN and your app don't seem to work together because webMANhas its own proxy server. For instance,on HEN, your app needs to be enabled first then after HEN + webMAN MOD.

However, what I suggest is that you implement the code within webMAN itself. This way, the webMAN proxy could increase download speeds similar to how your app does.

I know the app is meant to bypass the updates and etc, but almost everyone, at least here in BRAZIL uses it to increase the download speed.

A game that normally takes 120 minutes with your app it is down to 30 or less.

**Comment by Edw590** [comment]
Oh, unfortunately I don't have enough time to try to implement the thing in webMAN... Maybe Aldo could be interested in trying himself? Or maybe not, no idea. I don't think I can... I may lack the time needed to learn how to program in for the PS3 (I never did). I'm sorry.

Yep I've heard about that. And I still have absolutely no idea how it increases speeds ahaha. It's just a proxy that makes the traffic pass through the phone first. Should be the same as downloading directly. But if it really helps, I can't get why. But cool it does help. And I didn't know webMAN had a proxy itself and even that it has issues with mine. Damn.

Curiosity, do you know if it helps on the PS4/PS5/PC too? Or just the PS3? (I'm just laughing right now, just watched a video of a download going from 276 min to 14 min AHAHAHA, with just the proxy, wtf AHAHAHA. This is dark magic to me, but if it works, cool! ahaha)

**EDIT:** did anyone try with another proxy? Just curious if it's specific to this app or not. Maybe the traffic just has to go through the phone (and still, who knows why). Or maybe it's the app's code that does the magic somehow.
